### ISSUE TITLE
error while executing predict_gui.exe

### ISSUE THREAD

**Issue by R-Raph** [UoA-eResearch/leapmotion_gestures#18]
Hi i have an error while executing predict_gui.exe 

Traceback (most recent call last):                                                                                                                                              File "predict_gui.py", line 150, in <module>                                                                                                                                  File "src\leap_methods.py", line 26, in collect_frame                                                                                                                         File "lib\site-packages\websocket\_core.py", line 515, in create_connection                                                                                                   File "lib\site-packages\websocket\_core.py", line 223, in connect                                                                                                             File "lib\site-packages\websocket\_http.py", line 121, in connect                                                                                                             File "lib\site-packages\websocket\_http.py", line 201, in _open_socket                                                                                                        File "lib\site-packages\websocket\_http.py", line 176, in _open_socket                                                                                                      ConnectionRefusedError: [WinError 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée                                                 [17596] Failed to execute script predict_gui 
(traduction) : ConnectionRefusedError : [WinError 10061] no connexion could be established as the target computer has expressively refused it

I tried with 2 different internet connexion 
have you an idea of why this is occuring ? 

Thanks

**Comment by neon-ninja** [comment]
Is your leapmotion accessible over web socket? You have to enable it in the leapmotion settings

**Comment by R-Raph** [comment]
I think it is enabled by default in Gemini version. I dont know where to dig if not

Edit : it is not. Still dont know if in Can set It up somewhere??

**Comment by R-Raph** [comment]
Ok i tried to install the orion tracking software 4.1 and it. Work seems like the New Gemini version doesnt allow web app

Edit : indeed i talked to ultraleap support and they deactivated the option to use web app. They told me that they were probably going to put this feature back on in the future but that it wasn't currently in progress...
